name: CI
on:
  push:
    branches:
      - '**'
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Disable DotNet First Usage Messsage
        run: touch "$HOME/.dotnet/$(dotnet --version).dotnetFirstUseSentinel"
      - name: Install sonar-scanner
        run: dotnet tool install -g dotnet-sonarscanner
      - name: Begin sonar scanning
        run: dotnet-sonarscanner begin -o:nazmialtun-github -k:NazmiAltun_prometheus-netruntime-metrics -d:sonar.host.url='https://sonarcloud.io' -d:sonar.cs.opencover.reportsPaths:'coverage/*.xml -d:sonar.cs.vstest.reportsPaths=coverage/*.trx
      - name: Run Tests
        run: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:CoverletOutput=../../coverage/integration.xml
      - name: End sonar scanning
        run: dotnet-sonarscanner end 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}